swagger: '2.0'
info:
  version: v1
  title: VMSCore_APIDocumentation
host: 'localhost:55983'
schemes:
  - http
paths:
  /api/AliasUsers:
    get:
      description: "Access to API Documentation"
      tags:
        - AliasUsers
      operationId: AliasUsers_GetAliasUsers
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/AliasUsers'
    post:
      tags:
        - AliasUsers
      operationId: AliasUsers_PostAliasUsers
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - name: aliasUsers
          in: body
          required: true
          schema:
            $ref: '#/definitions/AliasUsers'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AliasUsers'
  '/api/AliasUsers/{id}':
    get:
      tags:
        - AliasUsers
      operationId: AliasUsers_GetAliasUsers
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AliasUsers'
    put:
      tags:
        - AliasUsers
      operationId: AliasUsers_PutAliasUsers
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: aliasUsers
          in: body
          required: true
          schema:
            $ref: '#/definitions/AliasUsers'
      responses:
        '204':
          description: No Content
    delete:
      tags:
        - AliasUsers
      operationId: AliasUsers_DeleteAliasUsers
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AliasUsers'
  /api/Values:
    get:
      tags:
        - Values
      operationId: Values_Get
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
    post:
      tags:
        - Values
      operationId: Values_Post
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces: []
      parameters:
        - name: value
          in: body
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
  '/api/Values/{id}':
    get:
      tags:
        - Values
      operationId: Values_Get
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            type: string
    put:
      tags:
        - Values
      operationId: Values_Put
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: value
          in: body
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
    delete:
      tags:
        - Values
      operationId: Values_Delete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '204':
          description: No Content
definitions:
  AliasUsers:
    type: object
    properties:
      UserID:
        format: int32
        type: integer
      UserName:
        type: string
      FirstName:
        type: string
      LastName:
        type: string
      Active:
        type: boolean
      DomainName:
        type: string
      Email:
        type: string
      Location:
        type: string